### ISSUE TITLE
inefficient execution of tracers?

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/reproman#410]
while running tracing (e.g.  `reproman execute -r localshell --trace -- python -m nose -s -v reproman/tests/test_api.py`) you can see that there is not that much of activity from reproman/python/dpkg/conda either in CPU or disk.  Overall it runs really slow, must be due to some blocking (ATM though running jitsi so it is known to slow things down).  We need to figure out how to make it faster.

this is my localshell resource definition
```yaml
localshell:
  id: thebest
  name: localshell
  status: available
  type: shell
```
